const Home = () => {
  return (
    <>
      <head>
        <title>Reunion ...nasima ocima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main></main>
    </>
  );
};

export default Home;
