import Head from 'next/head';
import Link from 'next/link';
import Menu from '../components/Menu';
import Footer from '../components/Footer';

const Home = () => {
  return (
    <>
      <Head>
        <title>Reunion ...nasima ocima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Menu />
        <h1>
          <Link href="/">
            <a>Reunion hokus pokus...</a>
          </Link>
        </h1>
        <Footer />
      </main>
    </>
  );
};

export default Home;
